name: Build, test, package

on: [push,pull_request]

env:
  itk-git-tag: "v5.3.0"
  itk-wheel-tag: "v5.3.0"
  ITKMeshToPolyData-git-tag: "v0.10.0"

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@363c0f6ebf0124fda8f9b69ae2f1cda89dc1fe53
    with:
      itk-module-deps: 'MeshToPolyData@v0.10.0'
      
  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@363c0f6ebf0124fda8f9b69ae2f1cda89dc1fe53
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.10.0'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
