name: Build, test, package

on: [push,pull_request]

env:
  itk-git-tag: "v5.3.0"
  itk-wheel-tag: "v5.3.0"
  ITKMeshToPolyData-git-tag: "v0.10.0"

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@3ff507f9f30ceb8617ff42e0d013c9f411591d50
    with:
      itk-module-deps: 'MeshToPolyData@v0.10.0'
      
  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@3ff507f9f30ceb8617ff42e0d013c9f411591d50
    with:
      itk-module-deps: 'InsightSoftwareConsortium/ITKMeshToPolyData@v0.10.0'
      itk-python-package-org: 'tbirdso'
      itk-python-package-tag: '976bc4e177a595c902074817cbadab9a55d13e1e'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
